version: "3"
services:
  db:
    image: mariadb:10.5.9
    container_name: hacknock_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - backend
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -P ${MYSQL_PORT} -u root -p${MYSQL_ROOT_PASSWORD}
      timeout: 20s
      interval: 5s
      retries: 3
  web:
    container_name: hacknock_web
    environment:
      HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CON_LIMIT: ${CON_LIMIT}
      WEB_PORT: ${WEB_PORT}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: development
    build:
      context: .
      args:
        - WEB_PORT=${WEB_PORT}
        - NODE_ENV=development
    ports:
      - 127.0.0.1:${WEB_PORT}:${WEB_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
