// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivers

import (
	"context"
	"github.com/Hacknock/leadyou/adapters/controllers"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeLeadyouDriver(ctx context.Context) (Leadyou, error) {
	echoEcho := echo.New()
	leadyou := controllers.NewWebController()
	driversLeadyou := NewWebDriver(echoEcho, leadyou)
	return driversLeadyou, nil
}
