import React, { useState } from "react";
import { useTranslation } from "react-i18next";
import OneLineField from "./forms/OneLineField";
import MultiLineField from "./forms/MultiLineField";
import UploadFile from "./forms/UploadFile";
import "./Editor.css";

type Props = {
  lang: string;
  owner: string | null;
  repo: string | null;
  autoFill: boolean;
};

export default function Editor(props: Props) {
  const { lang, owner, repo, autoFill } = props;
  const { t } = useTranslation();

  const [showAlert, setShowAlert] = useState(false);

  return (
    <div className="editor">
      <div className="edit-area">
        <h2>Input Form</h2>
        <div className="edit-inner">
          <form>
            <MultiLineField
              title={"Short Description"}
              hiddenTitle={false}
              description={"Please write down a short description of the project."}
              required={true}
              multiple={true}
              placeholder={null}
              maxLength={500}
            />
            <OneLineField
              title={"Badges"}
              hiddenTitle={false}
              description={"Please input the badges."}
              required={false}
              multiple={true}
              placeholder={null}
              maxLength={300}
            />
            <UploadFile
              title={"Demo"}
              hiddenTitle={false}
              description={"Please upload an image and input a description for a demonstration."}
              required={false}
              multiple={true}
              placeholder={null}
              maxLength={500}
            />
            <p className="proviso">
              If you generate a README, you are deemed to have accepted the
              <a href="?scene=document&pageid=terms-of-service">Terms of Service</a>. And if you
              upload README that is generated by LEADYOU to your public repository on GitHub, it
              will be on
              <a href="/">New Generated READMEs</a>. If you do not want it, please refer
              <a href="?scene=document&pageid=help">Help</a> page.
            </p>
            <input type="submit" value="Generate" />
            {showAlert && <p className="fill-alert"></p>}
          </form>
        </div>
      </div>
      <div className="preview-area">
        <h2>Preview README</h2>
        <div className="md-content"></div>
      </div>
    </div>
  );
}
