name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-commit:
    name: Build & Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-commit
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        id: deployment
